version: '3'

services:
  db:
    image: postgres:latest
    privileged: true
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "jrachka"
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas:latest
    ports:
      - "54321:80"
  redis:
    image: redis:latest
    ports:
      - '6380:6379'