# Generated by Django 4.1.4 on 2022-12-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("api_key", models.CharField(max_length=128, unique=True)),
                (
                    "check_type",
                    models.CharField(
                        choices=[("Kitchen", "kitchen"), ("Client", "client")],
                        default="Kitchen",
                        max_length=64,
                    ),
                ),
                ("point_id", models.IntegerField(help_text="Related shop id")),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Kitchen", "kitchen"), ("Client", "client")],
                        default="Kitchen",
                        max_length=64,
                    ),
                ),
                ("order", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "new"),
                            ("Rendered", "rendered"),
                            ("Printed", "printed"),
                        ],
                        default="New",
                        max_length=64,
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, upload_to="pdf")),
                (
                    "printer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ticket_service_api.printer",
                    ),
                ),
            ],
        ),
    ]
