# Generated by Django 4.1.4 on 2023-01-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_service_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="printer_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ticket_service_api.printer",
            ),
        ),
    ]
