# Generated by Django 4.1.4 on 2023-01-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_service_api", "0002_alter_check_printer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdf"),
        ),
        migrations.AlterField(
            model_name="check",
            name="printer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ticket_service_api.printer",
            ),
        ),
    ]
